spring.application.name=orm-learn

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn
spring.datasource.username=root
spring.datasource.password=root

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework=info
logging.level.com.cognizant.ormlearn=debug